spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotel
    username: "root"
    password: "root"
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  application:
    name: Hotel-Service
  zipkin:
    base-url: http://127.0.0.1:9411/
  cloud:
    config:
      enabled: true
      uri: http://localhost:8098
  mvc:
   pathmatch:
      matching-strategy: ant-path-matcher
 # profiles:
 #   active:
 #   - QA
  jackson:
    serialization:
      fail-on-empty-beans: false  
server:
  port: 8092
  
jpa:
   hibernate:
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl